default:
  tags:
    - shell-runner-38

stages:
  - build_temp_image
  - smoke_test
  - regression_test
  - nodiff_test
  - push_release
  - package
  - push_ali

variables:
  PROJECT_NAME: barcode_demux
  TEMP_TAG: tmp-$CI_COMMIT_SHORT_SHA
  BARCODE_SMOKE_TEST_DIR: /data/CI_CD_DATASETS/PROJECT_barcode/smoke_test
  # ASSIGN_BARCODE_TEST_DIR: /data/CI_CD_DATASETS/PROJECT_primer/assign_barcode_test
  RELEASE_TAG: $CI_COMMIT_TAG
  CI_REGISTRY_IMAGE: 192.168.3.38:5000/algo/barcode_demux
  # GIT_SUBMODULE_STRATEGY: recursive
  ALI_ACR_REGISTRY_IMAGE: geneus-registry.cn-hongkong.cr.aliyuncs.com/algo/barcode_demux
  REFS_DIR: /data/CI_CD_DATASETS/REF_GENOMES



# ===============================
# 1. Push 到 main 分支流程
# ===============================


build_temp_image:
  stage: build_temp_image
  script:
    - echo `whoami`
    # - bash -c 'source ~/.bashrc && echo `python --version` '
    - echo "📦 Building temp image..."
    - DOCKER_BUILDKIT=1 docker build -t $PROJECT_NAME:$TEMP_TAG .
  except:
    - tags
    - web


adapter_smoke_test:
  stage: smoke_test
  script:
    - echo `whoami`
    - echo "🔥 Smoke testing temp image..."
    - echo "冒烟测试文件"
    - bash -c 'source ~/.bashrc && python -u python_scripts/run_barcode_test.py --test-file-dir ${BARCODE_SMOKE_TEST_DIR} --docker-image ${PROJECT_NAME}:${TEMP_TAG} --test-type smoke'
  except:
    - tags
    - web


push_release:
  stage: push_release
  script:
    - echo `whoami`
    - echo "📤 Pushing release image..."
    - docker tag $PROJECT_NAME:$TEMP_TAG $CI_REGISTRY_IMAGE:$RELEASE_TAG
    - docker push $CI_REGISTRY_IMAGE:$RELEASE_TAG
    - echo "📤 Pushing release image DONE. $CI_REGISTRY_IMAGE:$RELEASE_TAG"
  only:
    - tags


package:
  stage: package
  script:
    - echo "📦 Generating temporary package..."
    - docker save -o $PROJECT_NAME-$RELEASE_TAG.tar $CI_REGISTRY_IMAGE:$RELEASE_TAG
    - mv $PROJECT_NAME-$RELEASE_TAG.tar /dataLab/Geneus110/BC/共享文件夹/算法镜像/adacus
  only:
    - tags


push_ali:
  stage: push_ali
  script:
    - echo "📤 Pushing release image to ali"

    - docker tag $CI_REGISTRY_IMAGE:$RELEASE_TAG  $ALI_ACR_REGISTRY_IMAGE:$RELEASE_TAG
    - docker push $ALI_ACR_REGISTRY_IMAGE:$RELEASE_TAG
  only:
    - tags



